# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperatura.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'temperatura.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperatura.proto\"\x1c\n\x0bTempEntrada\x12\r\n\x05valor\x18\x01 \x01(\x02\"\x1f\n\nTempSalida\x12\x11\n\tresultado\x18\x01 \x01(\x02\x32o\n\x0bTemperatura\x12/\n\x12\x43\x65lsiusAFahrenheit\x12\x0c.TempEntrada\x1a\x0b.TempSalida\x12/\n\x12\x46\x61hrenheitACelsius\x12\x0c.TempEntrada\x1a\x0b.TempSalidab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperatura_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPENTRADA']._serialized_start=21
  _globals['_TEMPENTRADA']._serialized_end=49
  _globals['_TEMPSALIDA']._serialized_start=51
  _globals['_TEMPSALIDA']._serialized_end=82
  _globals['_TEMPERATURA']._serialized_start=84
  _globals['_TEMPERATURA']._serialized_end=195
# @@protoc_insertion_point(module_scope)
